# name: hot_sport
# description: A new Flutter package project.
# version: 1.0.0
# homepage: uuu

# environment:
#   sdk: '>=2.17.0 <3.0.0'
#   flutter: ">=1.17.0"

# dependencies:
#   flutter:
#     sdk: flutter
#   extended_image: 4.1.0
#   get_it: ^7.2.0
#   get: ^4.1.3
#   badges: ^3.0.2
#   stacked: ^3.1.0+3
#   video_player: ^2.1.6
#   lottie: 2.1.0
#   google_fonts: ^2.1.0
#   cached_network_image: ^3.2.3
#   font_awesome_flutter: ^10.4.0
#   velocity_x: 3.6.0  #use shimmer
#   decimal: ^2.2.0

# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^2.0.0

# # For information on the generic Dart part of this file, see the
# # following page: https://dart.dev/tools/pub/pubspec

# # The following section is specific to Flutter packages.
# flutter:
#   assets:
#     - assets/images/
#   fonts:
#     - family: 阿里妈妈东方大楷
#       fonts:
#         - asset: assets/fonts/阿里妈妈东方大楷/Alimama_DongFangDaKai_Regular.ttf
#     - family: 阿里妈妈数黑体
#       fonts:
#         - asset: assets/fonts/阿里妈妈数黑体/Alimama_ShuHeiTi_Bold.ttf
#     - family: 得意黑斜体
#       fonts:
#         - asset: assets/fonts/得意黑/Smiley_Sans_Oblique_斜体.ttf
#     - family: 钉钉进步体
#       fonts:
#         - asset: assets/fonts/钉钉进步体/DingTalk_JinBuTi_Regular.ttf
#     - family: 站酷高端黑
#       fonts:
#         - asset: assets/fonts/zcool-gdh_Regular.ttf
#     - family: 站酷酷黑
#       fonts:
#         - asset: assets/fonts/ZCOOL_KuHei_Regular.ttf
#     - family: 阿里巴巴普惠体2.0
#       fonts:
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_35_Thin_35_Thin.ttf
#           weight: 200
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_45_Light_45_Light.ttf
#           weight: 300
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_55_Regular_55_Regular.ttf
#           weight: 400
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_65_Medium_65_Medium.ttf
#           weight: 500
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_95_ExtraBold_95_ExtraBold.ttf
#           weight: 800
#         - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_105_Heavy_105_Heavy.ttf
#           weight: 900
        
#     - family: W01
#       fonts:
#         - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W01_W01.ttf
#           style: normal
#     - family: W02
#       fonts:
#         - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W02_W02.ttf
#           style: normal
#     - family: W03
#       fonts:
#         - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W03_W03.ttf
#           style: normal
#     - family: W04
#       fonts:
#         - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W04_W04.ttf
#           style: normal
#     - family: W05
#       fonts:
#         - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W05_W05.ttf
#           style: normal

#     - family: 思源黑体简体
#       fonts:
#         - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Regular.otf
#           weight: 400
#         - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Medium_Medium.otf
#           weight: 500    
#         - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Bold.otf
#           weight: 700
#         - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Heavy_Heavy.otf
#           weight: 900

#     - family: 白无常可可体
#       fonts:
#         - asset: assets/fonts/白无常可可体/可可体细.ttf
#           weight: 300
#         - asset: assets/fonts/白无常可可体/可可体常规.ttf
#           weight: 400    
        # - asset: assets/fonts/白无常可可体/可可粗体.ttf
        #   weight: 700
#     - family: 思源宋体
#       fonts:
#         - asset: assets/fonts/Source_Han_Serif_SC_Light_Light.otf
#           weight: 300



#------ 字体删减后的
name: hot_sport
description: A new Flutter package project.
version: 1.0.0
homepage: uuu

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  extended_image: 8.1.1
  get_it: ^7.2.0
  get: ^4.1.3
  badges: ^3.0.2
  stacked: ^3.1.0+3
  video_player: ^2.7.2
  lottie: 2.1.0
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.6.0
  velocity_x: 4.1.2  #use shimmer
  decimal: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
  fonts:
    - family: 阿里妈妈东方大楷
      fonts:
        - asset: assets/fonts/阿里妈妈东方大楷/Alimama_DongFangDaKai_Regular.ttf
    - family: 阿里妈妈数黑体
      fonts:
        - asset: assets/fonts/阿里妈妈数黑体/Alimama_ShuHeiTi_Bold.ttf
    - family: 得意黑斜体
      fonts:
        - asset: assets/fonts/得意黑/Smiley_Sans_Oblique_斜体.ttf
    - family: 钉钉进步体
      fonts:
        - asset: assets/fonts/钉钉进步体/DingTalk_JinBuTi_Regular.ttf
    - family: 站酷高端黑
      fonts:
        - asset: assets/fonts/zcool-gdh_Regular.ttf
    - family: 阿里巴巴普惠体2.0
      fonts:
        - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_55_Regular_55_Regular.ttf
          weight: 400
        - asset: assets/fonts/阿里巴巴普惠体 2.0/Alibaba_PuHuiTi_2.0_95_ExtraBold_95_ExtraBold.ttf
          weight: 800
        
    - family: W03
      fonts:
        - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W03_W03.ttf
          style: normal
    - family: W05
      fonts:
        - asset: assets/fonts/站酷仓耳渔阳体/TsangerYuYangT_W05_W05.ttf
          style: normal

    - family: 思源黑体简体
      fonts:
        - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Regular.otf
          weight: 400
        - asset: assets/fonts/思源黑体-简体中文/Source_Han_Sans_SC_Bold.otf
          weight: 700

    - family: 白无常可可体
      fonts:
        - asset: assets/fonts/白无常可可体/可可体常规.ttf
          weight: 400  
        - asset: assets/fonts/白无常可可体/可可粗体.ttf
          weight: 700  
    - family: 思源宋体
      fonts:
        - asset: assets/fonts/Source_Han_Serif_SC_Light_Light.otf
          weight: 300


